- alias: 'Lights on when home after sunset'
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
    - platform: sun
      event: sunset
  condition:  
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: 
        - light.artemide
        - light.gang

- alias: 'Bedroom Light - Adjust Brightness'
  trigger:
    platform: state
    entity_id: input_number.bedroom_brightness
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.schlafzimmerlampe
        brightness: "{{ trigger.to_state.state | int }}"