- alias: 'Lights on when home after sunset'
  trigger:
    - platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
    - platform: sun
      event: sunset
  condition:  
    condition: and
    conditions:
      - condition: sun
        after: sunset
      - condition: state
        entity_id: group.all_devices
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.artemide