<<<<<<< Updated upstream
- alias: Globus an.
  trigger:
    platform: time
    at: 18:00
  action:
    service: switch.turn_on
    entity_id: switch.globus

- alias: Globus aus
  trigger:
    platform: time
    at: 23:00
  action:
    service: switch.turn_off
    entity_id: switch.globus
=======
>>>>>>> Stashed changes
