- platform: yr
  name: yr
  monitored_conditions:
    - temperature
    - pressure
    - symbol

- platform: wunderground
  name: Wunderground
  api_key: !secret wunderground_key
  monitored_conditions:
    - alerts
    - dewpoint_c
    - temp_c

- platform: moon

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
  minute:
    20